# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = "${custom.worldpath}$all"

[package]
disabled = true

[python]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[directory]
disabled = true # use worldpath

[container]
disabled = true

[git_branch]
style = "bold 220"

[nix_shell]
disabled = true

[docker_context]
disabled = true

# Add a custom module that runs worldpath
[custom.worldpath]
command = "worldpath --full"
when = true
format = "[$output]($style) "
style = "bold cyan"

